### ISSUE TITLE
Auto indent issue

### ISSUE THREAD

**Issue by elclanrs** [jwalton512/vim-blade#1]
Trying to use this plugin to develop in Laravel. Syntax looks nice, but the indentation doesn't seem to work properly. Given this sample code below, when I press `o` at the cursor `#` the new line `|` starts at the very beginning not at the proper indentation level.

```
@foreach ($articles as $article)
   <h1>{{ $article->title }}</h1>
   <p>{{ $article->content }}</p>#
|
@endforeach
```

When it should be:

```
@foreach ($articles as $article)
   <h1>{{ $article->title }}</h1>
   <p>{{ $article->content }}</p>#
   |
@endforeach
```

This happens at any indentation level. Any ideas how to fix it?

**Comment by bayucakra20** [comment]
@elclanrs thanks bro, it also worked for me.

**Comment by kevariable** [comment]
> Got a permanent fix, at least for now, this works for Blade, PHP and HTML syntax with correct autoindent:
> 
> ```
> autocmd BufNewFile,BufRead *.blade.php set ft=html | set ft=phtml | set ft=blade " Fix blade auto-indent
> ```

after putting this configuration, my blade can't use emmed why?
