### ISSUE TITLE
Single-line comments are overriding }}

### ISSUE THREAD

**Issue by tremby** [jwalton512/vim-blade#22]
```
<div>
	TODO: looks selection
	{{ Form::hidden('look1', 'look1') // TODO }}
</div>
```

Rendering as

![screen shot 2014-05-22 at 5 00 48 pm](https://cloud.githubusercontent.com/assets/199635/3061730/564c796e-e20d-11e3-822c-9adb42032371.png)

The `}}` should override the comment. At present the }} is still rendered as a comment, and the PHP mode has not been cancelled, so the next line (`</div>`, HTML) is still rendered as PHP.

**Comment by jwalton512** [comment]
this seems to render correctly with new updates.
