### ISSUE TITLE
Indent issue

### ISSUE THREAD

**Issue by jrean** [jwalton512/vim-blade#28]
Hi,

I have a problem with indentation on *.blade.php files.
I was using this trick based on the following issue https://github.com/xsbeats/vim-blade/issues/1

```
autocmd BufNewFile,BufRead *.blade.php set ft=html | set ft=phtml | set ft=blade " Fix blade auto-indent
```

```
@foreach ($articles as $article)
   <h1>{{ $article->title }}</h1>
   <p>{{ $article->content }}</p>#
|
@endforeach
```
When it should be
```
@foreach ($articles as $article)
   <h1>{{ $article->title }}</h1>
   <p>{{ $article->content }}</p>#
   |
@endforeach
```

The following command outputs:
```
:set ft?
filtetype=blade
```

How to solve it?

Regards,

**Comment by rendom** [comment]
+1 on integrate indenting.

**Comment by xsbeats** [comment]
@arthurvr @rendom unfortunately I don't really have the know how to implement any type of reliable indenting.  I would encourage anyone that does have the knowledge to contribute.

**Comment by rendom** [comment]
A good start can be to include html indentation?
https://github.com/rendom/vim-blade/blob/master/syntax/blade.vim#L15

**Comment by jwalton512** [comment]
rebuilt from scratch.  included indenting this time around.  there will likely be some kinks to work out.

**Comment by bx2** [comment]
@rendom, your quick-fix works just fine. Adding the basic HTML syntax solved all the issues for me (I've installed via rendom's fork).
