### ISSUE TITLE
Does not work with matchit.vim (fix linked)

### ISSUE THREAD

**Issue by allendoerfer** [jwalton512/vim-blade#36]
The plugin breaks the matchit.vim plugin, which is shipped with vim by default and lets you jump between tag pairs.

Here is a fix, that tells matchit to use the html regexes:

http://stackoverflow.com/questions/28230238/matchit-not-working-in-customed-filetype/28235431#28235431

To further improve it one could add regexes for blade-tags.

**Comment by jwalton512** [comment]
I don't use matchit.  Can you confirm this issue still exists with the most recent updates.  I assume that it will as I haven't included any logic similar to what you linked.

**Comment by jwalton512** [comment]
closing for now.  @allendoerfer if you notice this issue still exists, please let me know.

**Comment by adriaanzon** [comment]
As of e2a1686, Blade directives have matchit support too :smile:
