### ISSUE TITLE
A blade file that crashes my VIM

### ISSUE THREAD

**Issue by moccalotto** [jwalton512/vim-blade#44]
The code below SOMETIMES crashes my vim when I try to type a new echo tag "{{" 
Vim simply stalls as soon as I type the first curlybrace in insert mode.

I've tried disabling all plugins.

I can paste {{ }} blocks if I created them in other files, so the problem seems to apply to insert mode only

My `vimrc`: http://pastebin.com/6HZs9xvg
The file: http://pastebin.com/5aA205GA

**Comment by jwalton512** [comment]
As there have been many updates since this issue was added, please determine if the issue still exists in the current version.
