### ISSUE TITLE
Auto indent issues

### ISSUE THREAD

**Issue by lcjury** [jwalton512/vim-blade#46]
I have the following problem with the auto indentation of this plugin (don't really know if is really a problem), when I let the plugin auto-indent my .blade files, the html part of the code are indented all at the same level.

<img width="420" alt="captura de pantalla 2016-04-26 a las 12 45 51 1" src="https://cloud.githubusercontent.com/assets/1194606/14824566/e4e518e6-0bac-11e6-846d-e32db46d40b9.png">

I can use `set ft=html` and indent everything with `ggvG=` and then return to `set ft=blade` but it is really annoying.

**Comment by jwalton512** [comment]
resolved with #47
