### ISSUE TITLE
The syntax for blade.php files is not set automatically to "blade"

### ISSUE THREAD

**Issue by j4g0** [jwalton512/vim-blade#63]
I got vim-blade as part of sheerun/vim-polyglot which I installed via vundle on Linux Mint 18 Sarah 64 bit. The syntax works fine but I have to manually set it since vim does not seem to recognize viewname.blade.php as a blade file but as php. My airline as well as the set filetype? command say so. My workaround so far (thx to romainl) is an autocommand in my vimrc:

augroup blade
autocmd!
autocmd BufNewFile,BufRead *.blade.php set filetype=blade
augroup END

but since no one else mentioned it as an issue so far, is was wondering where I could have  screwed up during installation :)

**Comment by xp-bar** [comment]
I've also had this issue! I installed the package separately from `polygot` and my file had only php syntax highlighting - @j4g0 's solution fixed it for me however!

**Comment by rku4er** [comment]
Same problem. Simply added this line to my local .vimrc:
`autocmd BufRead,BufNewFile *.blade.php set filetype=blade`

**Comment by benyaminl** [comment]
> Same problem. Simply added this line to my local .vimrc:
> `autocmd BufRead,BufNewFile *.blade.php set filetype=blade`

Thank you. It works well!
![image](https://user-images.githubusercontent.com/2817332/63213485-2cc54a80-c137-11e9-9003-245a64091c15.png)

**Comment by rafgugi** [comment]
thanks, but not why I need to add `syntax=blade` for me to make it work

```vim
augroup file_blade_php
  autocmd BufRead,BufNewFile *.blade.php setlocal ts=2 sts=2 sw=2 filetype=blade syntax=blade expandtab
augroup END
```

**Comment by adriaanzon** [comment]
It shouldn't be necessary to add this configuration yourself. If the plugin was installed correctly, the [ftdetect/blade.vim](https://github.com/jwalton512/vim-blade/blob/master/ftdetect/blade.vim) file will handle setting the filetype to 'blade'.

If this isn't working for you, you can debug where the filetype was last set using `:verbose set ft?`.
