### ISSUE TITLE
Add syntax from the laravel plugin

### ISSUE THREAD

**Issue by kertahayu** [jwalton512/vim-blade#72]
Example add :
`@role @androle` syntax from [https://github.com/spatie/laravel-permission](url).
`@permission @endpermission @ability @endability` syntax from  [https://github.com/santigarcor/laratrust](url).

**Comment by jwalton512** [comment]
@dele-corporate, thank you for the feedback.  The goal of this plugin is to care for the syntax as officially offered by Laravel.

There is functionality to add your own custom directives within your own `.vimrc`

For example:
```
let g:blade_custom_directives = ['role', 'androle']
let g:blade_custom_directives_pairs = {
      \   'permission': 'endpermission',
      \   'ability': 'endability',
      \ }
```
